name: ShopOnSign
version: "1.1.0"
api: [3.0.0]
main: brokiem\ShopOnSign\EconomyShop
author: onebone, brokiem
description: Shop On Sign Plugin For PMMP
depend: [EconomyAPI]

permissions:
 economyshop.*:
  description: Allows all functions in ShopOnSign
  default: op
  children:
   economyshop.shop.*:
    description: Allows all functions about ShopOnSign
    default: op
    children:
     economyshop.shop.buy:
      description: Allows player to buy from shop
      default: true
     economyshop.shop.create:
      description: Allows player to create shop
      default: op
     economyshop.shop.remove:
      description: Allows player to remove shop
      default: op
